/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20 from "./ERC20";
export * as greetingsRegistry from "./GreetingsRegistry";
export * as interfaces from "./Interfaces";
